export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_MEMBERS_PENDING = 'REQUEST_MEMBERS_PENDING';
export const REQUEST_MEMBERS_SUCCESS = 'REQUEST_MEMBERS_SUCCESS';
export const REQUEST_MEMBERS_FAILED = 'REQUEST_MEMBERS_FAILED';